version: "3"
services:
  frontend:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tdp-exercise
    ports:
      - 5000:80
    volumes:
      - ./:/home/node/app
    networks:
      - local
networks:
  local:
    driver: bridge